debug: true

udp:
  timeout: 2 # Reduce when bug is fixed
  connection_buffer: 16
  announce_buffer: 4096 # Unknown max size
  scraping_buffer: 32 # In reality [20] but 32 to match hardware and network reality

http:
  port: 6881
  compact: 1
  numwant: 100
  timeout: 2 # Reduce when bug is fixed
  peer_limit: 50000 # Limit of peers to keep looking in announce-list

# MOVE-FULL handshake in config?

tcp:
  timeout: 2 # Reduce when bug is fixed
  handshake_buffer: 4096 # Unknown max size
  state_message_buffer: 16 # Max size should be 5 
  message_buffer: 4096 # NOTE: LARGE? Need to look into how large this can be! - remember one bit for each piece?

client: 
  peer_id: '-TI2080-' # Prefix for TinyTorrent's peer_id. Upon startup this will be given a random suffix as: '-TI2080-12345689123'
  key: 'TINY:'